# =============================================================================
#  green_operator.jl
#
#  Real-space *Green operator* Γ⁰(x) of an infinite isotropic medium — the
#  regular part of the kernel of the Lippmann-Schwinger equation, evaluated
#  at a point x ≠ 0.
#
#  Where `green_dipole.jl` gives ∂G/∂x (the displacement generated by a point
#  force dipole), this file gives one derivative more: the *field* generated
#  by that dipole.  In elasticity
#
#       𝔾⁰_ijkl(x) = -[ ∂²G_ik/∂x_j∂x_l ]_{(ij)(kl)}
#
#  (the brackets denoting minor symmetrization), so that a uniform
#  polarization τ carried by a small volume V at the origin induces the
#  strain -V·𝔾⁰(x):τ at x.  In conduction the same object is minus the Hessian
#  of the scalar Green function, 𝔾⁰_ij = -∂²G/∂x_i∂x_j.
#
#  SIGN CONVENTION — the leading minus is not decoration.  The package follows
#  Brisard, Bertin & Legoll (2023), Eq. (9): the Green operator maps a
#  polarization onto *minus* the induced field,
#
#       ε = E - 𝔾⁰ * τ ,
#
#  which makes its Fourier symbol positive semi-definite (their Eq. (11),
#  Γ̂₀(k) = σ₀⁻¹ k⊗k/‖k‖² in conduction) and its interior average *plus* the
#  Hill tensor: averaging 𝔾⁰ over an ellipsoid containing the source returns
#  +ℙ.  The one-inclusion case is then the ε = -ℙ:τ that the rest of the
#  package already uses.  See `Interactions/api.jl`, which builds the
#  two-inclusion interaction tensors on top of this kernel, and the theory
#  page `theory/interaction_tensors.md` for the comparison with Molinari &
#  El Mouden (1996), who use the opposite sign.
#
#  Isotropic reference only in this file.  The anisotropic counterpart is the
#  Barnett-Willis angular integral of `green_aniso.jl`, which also owns the
#  `green_operator` dispatcher over both.
#
#  Public API vs kernel.  The exported `green_operator_iso` returns a `Tens`,
#  like every other tensor-valued entry point of the package.  The `_`-prefixed
#  methods return the bare `SArray` and are what the interaction kernels call:
#  wrapping costs about 1.4× time and ~900 B per evaluation, which is
#  irrelevant once but decisive inside a quadrature that evaluates the kernel
#  millions of times per interaction tensor.
# =============================================================================

"""
    green_operator_iso(C₀::TensISO{4,3}, x) -> Tens{4,3}

Real-space Green operator ``\\mathbb{G}^0`` of an infinite isotropic elastic
matrix `C₀`, evaluated at `x ≠ 0`:

```math
\\mathbb{G}^0_{ijkl}(x)
  = -\\Big[\\frac{\\partial^2 G_{ik}}{\\partial x_j \\partial x_l}(x)\\Big]_{(ij)(kl)} ,
```

where ``G`` is the Kelvin Green function and the brackets denote
symmetrization with respect to ``(i,j)`` and ``(k,l)``. The leading minus is
the convention of [brisard2023](@cite) — see the
file header.

With ``r = \\|x\\|``, ``\\underline{n} = x/r`` and ``A = 1/(16\\pi\\mu(1-\\nu))``,
the second gradient of the Kelvin solution reads

```math
\\frac{\\partial^2 G_{ij}}{\\partial x_k \\partial x_l}
  = \\frac{A}{r^{3}}\\Big[(3-4\\nu)\\,\\delta_{ij}\\,(3 n_k n_l - \\delta_{kl})
    + \\delta_{ik}\\delta_{jl} + \\delta_{il}\\delta_{jk}
    - 3\\big(\\delta_{il} n_j n_k + \\delta_{jl} n_i n_k
           + \\delta_{ik} n_j n_l + \\delta_{jk} n_i n_l
           + \\delta_{kl} n_i n_j\\big)
    + 15\\, n_i n_j n_k n_l\\Big].
```

A uniform polarization ``\\tau`` carried by a volume ``V`` around the origin
induces the strain ``-V\\,\\mathbb{G}^0(x):\\tau`` at `x` — exact in the far
field, and *exact at any separation* when the source region is a ball, because
each component of ``\\mathbb{G}^0`` is then averaged over a region where it is
harmonic.

Returned as a `Tens{4,3}` with both minor symmetries and the major symmetry.
Throws a `DomainError` at the origin. Type-generic (`Float64`,
`ForwardDiff.Dual`, symbolic scalars).

See also [`green_gradient_iso`](@ref), [`dipole_displacement_iso`](@ref).
"""
green_operator_iso(C₀::TensND.TensISO{4, 3}, x::AbstractVector) =
    TensND.Tens(_green_operator_iso(C₀, x))

function _green_operator_iso(C₀::TensND.TensISO{4, 3}, x::AbstractVector)
    E, ν = extract_iso_moduli(C₀)
    return _green_operator_iso(E / (2 * (1 + ν)), ν, x)
end

function _green_operator_iso(μ, ν, x::AbstractVector)
    r = sqrt(x[1]^2 + x[2]^2 + x[3]^2)
    iszero(r) && throw(
        DomainError(
            x, "the Green operator of an infinite medium is singular at the origin"
        )
    )
    n = SVector{3}(x[1] / r, x[2] / r, x[3] / r)
    A = one(r) / (16 * π * μ * (1 - ν) * r^3)
    c = 3 - 4 * ν
    T = typeof(A)
    δ = (i, j) -> _δ(i, j, T)
    # H[i,j,k,l] = ∂²G_ij/∂x_k∂x_l
    H = @inbounds [
        A * (
                c * δ(i, j) * (3 * n[k] * n[l] - δ(k, l))
                + δ(i, k) * δ(j, l) + δ(i, l) * δ(j, k)
                - 3 * (
                    δ(i, l) * n[j] * n[k] + δ(j, l) * n[i] * n[k]
                    + δ(i, k) * n[j] * n[l] + δ(j, k) * n[i] * n[l]
                    + δ(k, l) * n[i] * n[j]
                )
                + 15 * n[i] * n[j] * n[k] * n[l]
            )
            for i in 1:3, j in 1:3, k in 1:3, l in 1:3
    ]
    # 𝔾⁰_ijkl = -[H_{ik,jl}]_{(ij)(kl)} — the double index swap is what turns
    # the displacement Hessian into the strain-to-polarization operator, and
    # the leading minus is the Brisard convention of the file header.
    return SArray{Tuple{3, 3, 3, 3}}(
        @inbounds [
            -(H[i, k, j, l] + H[j, k, i, l] + H[i, l, j, k] + H[j, l, i, k]) / 4
                for i in 1:3, j in 1:3, k in 1:3, l in 1:3
        ]
    )
end

"""
    green_operator_iso(K₀::TensISO{2,3}, x) -> Tens{2,3}

Conduction counterpart: minus the Hessian of the scalar Green function of an
infinite isotropic medium of conductivity ``\\sigma_0``,

```math
\\boldsymbol{G}^0_{ij}(x) = -\\frac{\\partial^2}{\\partial x_i \\partial x_j}
   \\frac{1}{4\\pi\\sigma_0 r}
 = \\frac{\\delta_{ij} - 3 n_i n_j}{4\\pi\\sigma_0 r^{3}} .
```

It is traceless away from the origin — the isotropic part of the interaction
between two distinct inclusions vanishes identically in conduction, exactly
as the deviatoric statement ``\\mathbb{G}^0_{iijj} = \\mathbb{G}^0_{ijij} = 0``
does in elasticity.

The order-2 objects follow the ``\\boldsymbol{\\sigma} \\equiv -\\underline{q}``
convention of the package (see the notation page): the field this kernel
transports is the gradient ``\\nabla T`` and the source is the flux
polarization ``\\underline{\\tau}_q``, so every sign matches the elastic case
symbol for symbol.
"""
green_operator_iso(K₀::TensND.TensISO{2, 3}, x::AbstractVector) =
    TensND.Tens(_green_operator_iso(K₀, x))

function _green_operator_iso(K₀::TensND.TensISO{2, 3}, x::AbstractVector)
    return _green_operator_iso_order2(extract_iso_conductivity(K₀), x)
end

function _green_operator_iso_order2(σ₀, x::AbstractVector)
    r = sqrt(x[1]^2 + x[2]^2 + x[3]^2)
    iszero(r) && throw(
        DomainError(
            x, "the Green operator of an infinite medium is singular at the origin"
        )
    )
    n = SVector{3}(x[1] / r, x[2] / r, x[3] / r)
    A = one(r) / (4 * π * σ₀ * r^3)
    T = typeof(A)
    return SArray{Tuple{3, 3}}(
        @inbounds [
            A * (_δ(i, j, T) - 3 * n[i] * n[j]) for i in 1:3, j in 1:3
        ]
    )
end

"""
    green_operator_iso(K₀::TensISO{2,2}, x) -> Tens{2,2}

Two-dimensional conduction counterpart, from ``G = -\\log r/(2\\pi\\sigma_0)``:

```math
\\boldsymbol{G}^0_{ij}(x) = \\frac{\\delta_{ij} - 2 n_i n_j}{2\\pi\\sigma_0 r^{2}} .
```

Multiplied by the area ``\\pi b^2`` of a source disk this is *literally* the
plane form given by [brisard2023](@cite),
``\\boldsymbol{T}^{ab} = \\frac{b^2}{2\\sigma_0 r^2}
  (\\boldsymbol{1} - 2\\,\\underline{n}\\otimes\\underline{n})``, which is the
sharpest available check that the package and the paper share one convention.
"""
green_operator_iso(K₀::TensND.TensISO{2, 2}, x::AbstractVector) =
    TensND.Tens(_green_operator_iso(K₀, x))

function _green_operator_iso(K₀::TensND.TensISO{2, 2}, x::AbstractVector)
    return _green_operator_iso_order2_2d(extract_iso_conductivity(K₀), x)
end

function _green_operator_iso_order2_2d(σ₀, x::AbstractVector)
    r = sqrt(x[1]^2 + x[2]^2)
    iszero(r) && throw(
        DomainError(
            x, "the Green operator of an infinite medium is singular at the origin"
        )
    )
    n = SVector{2}(x[1] / r, x[2] / r)
    A = one(r) / (2 * π * σ₀ * r^2)
    T = typeof(A)
    return SArray{Tuple{2, 2}}(
        @inbounds [
            A * (_δ(i, j, T) - 2 * n[i] * n[j]) for i in 1:2, j in 1:2
        ]
    )
end

"""
    green_operator_iso(C₀::TensISO{4,2}, x) -> Tens{4,2}

Plane-strain elastic Green operator of an infinite isotropic matrix. The
two-dimensional Kelvin solution is

```math
G_{ij}(x) = \\frac{1}{8\\pi\\mu(1-\\nu)}
   \\big[-(3-4\\nu)\\log r\\,\\delta_{ij} + n_i n_j\\big],
```

whose second gradient gives

```math
\\frac{\\partial^2 G_{ij}}{\\partial x_k \\partial x_l}
  = \\frac{A_2}{r^{2}}\\Big[(3-4\\nu)\\,\\delta_{ij}\\,(2 n_k n_l - \\delta_{kl})
    + \\delta_{ik}\\delta_{jl} + \\delta_{il}\\delta_{jk}
    - 2\\big(\\delta_{il} n_j n_k + \\delta_{jl} n_i n_k
           + \\delta_{ik} n_j n_l + \\delta_{jk} n_i n_l
           + \\delta_{kl} n_i n_j\\big)
    + 8\\, n_i n_j n_k n_l\\Big],
```

with ``A_2 = 1/(8\\pi\\mu(1-\\nu))``. `ν` is the plane-strain Poisson ratio of
the reference medium. The result is symmetrized — and negated, per the
convention of the file header — exactly as in 3D.
"""
green_operator_iso(C₀::TensND.TensISO{4, 2}, x::AbstractVector) =
    TensND.Tens(_green_operator_iso(C₀, x))

function _green_operator_iso(C₀::TensND.TensISO{4, 2}, x::AbstractVector)
    E, ν = extract_iso_moduli(C₀)
    return _green_operator_iso_2d(E / (2 * (1 + ν)), ν, x)
end

function _green_operator_iso_2d(μ, ν, x::AbstractVector)
    r = sqrt(x[1]^2 + x[2]^2)
    iszero(r) && throw(
        DomainError(
            x, "the Green operator of an infinite medium is singular at the origin"
        )
    )
    n = SVector{2}(x[1] / r, x[2] / r)
    A = one(r) / (8 * π * μ * (1 - ν) * r^2)
    c = 3 - 4 * ν
    T = typeof(A)
    δ = (i, j) -> _δ(i, j, T)
    H = @inbounds [
        A * (
                c * δ(i, j) * (2 * n[k] * n[l] - δ(k, l))
                + δ(i, k) * δ(j, l) + δ(i, l) * δ(j, k)
                - 2 * (
                    δ(i, l) * n[j] * n[k] + δ(j, l) * n[i] * n[k]
                    + δ(i, k) * n[j] * n[l] + δ(j, k) * n[i] * n[l]
                    + δ(k, l) * n[i] * n[j]
                )
                + 8 * n[i] * n[j] * n[k] * n[l]
            )
            for i in 1:2, j in 1:2, k in 1:2, l in 1:2
    ]
    return SArray{Tuple{2, 2, 2, 2}}(
        @inbounds [
            -(H[i, k, j, l] + H[j, k, i, l] + H[i, l, j, k] + H[j, l, i, k]) / 4
                for i in 1:2, j in 1:2, k in 1:2, l in 1:2
        ]
    )
end
